"""
reasoning/engine.py — NanoSIEM AI Reasoning Engine

Orchestrates all Gemini-powered reasoning tasks.
Receives Alert objects, selects the right prompt template,
calls Gemini, and returns structured AI output.

DESIGN CONSTRAINT:
  This module only operates on alerts that have already been generated.
  It never calls the detection engine, never reads raw events directly,
  and never makes detection decisions.
"""

from __future__ import annotations

import logging
import time
from dataclasses import dataclass
from typing import Any

from nano_siem.reasoning.gemini import GeminiClient, GeminiResponse
from nano_siem.reasoning.prompts import (
    SYSTEM_INSTRUCTION,
    analyst_explanation_prompt,
    executive_report_prompt,
    incident_summary_prompt,
    mitre_explanation_prompt,
    recommended_actions_prompt,
    threat_narrative_prompt,
)

logger = logging.getLogger(__name__)


@dataclass
class AIResult:
    """Result of an AI reasoning task."""
    task: str                    # explain | summary | mitre | recommend | report | narrative
    content: str                 # Markdown text from Gemini
    model: str
    prompt_tokens: int
    output_tokens: int
    elapsed_seconds: float
    cached: bool = False
    error: str | None = None

    @property
    def success(self) -> bool:
        return self.error is None

    def to_dict(self) -> dict[str, Any]:
        return {
            "task": self.task,
            "content": self.content,
            "model": self.model,
            "prompt_tokens": self.prompt_tokens,
            "output_tokens": self.output_tokens,
            "elapsed_seconds": self.elapsed_seconds,
            "cached": self.cached,
            "error": self.error,
            "success": self.success,
        }


class ReasoningEngine:
    """
    AI reasoning engine for NanoSIEM.

    All public methods take alert dicts (already generated by the detection
    engine) and return AIResult objects with Gemini-generated explanations.
    """

    def __init__(self, api_key: str | None = None) -> None:
        self._client = GeminiClient(api_key=api_key)
        self._stats = {
            "total_calls": 0,
            "cached_calls": 0,
            "failed_calls": 0,
            "total_tokens": 0,
        }

    @property
    def is_configured(self) -> bool:
        return self._client.is_configured

    async def _run(self, task: str, prompt: str) -> AIResult:
        """Run a prompt through Gemini and return an AIResult."""
        t0 = time.perf_counter()
        self._stats["total_calls"] += 1
        try:
            response: GeminiResponse = await self._client.generate(
                prompt=prompt,
                system_instruction=SYSTEM_INSTRUCTION,
            )
            elapsed = time.perf_counter() - t0
            if response.cached:
                self._stats["cached_calls"] += 1
            self._stats["total_tokens"] += response.output_tokens
            return AIResult(
                task=task,
                content=response.text,
                model=response.model,
                prompt_tokens=response.prompt_tokens,
                output_tokens=response.output_tokens,
                elapsed_seconds=round(elapsed, 2),
                cached=response.cached,
            )
        except Exception as e:
            self._stats["failed_calls"] += 1
            elapsed = time.perf_counter() - t0
            logger.error("Gemini call failed for task '%s': %s", task, e)
            return AIResult(
                task=task,
                content="",
                model="gemini-2.5-flash",
                prompt_tokens=0,
                output_tokens=0,
                elapsed_seconds=round(elapsed, 2),
                error=str(e),
            )

    # ── Public API ────────────────────────────────────────────────────────────

    async def explain_alert(self, alert: dict) -> AIResult:
        """
        Generate an analyst-level explanation of a single alert.
        Explains what happened, why the alert fired, and what to investigate.
        """
        prompt = analyst_explanation_prompt(alert)
        return await self._run("explain", prompt)

    async def summarize_incident(self, alerts: list[dict]) -> AIResult:
        """
        Generate an incident summary across multiple related alerts.
        Produces a structured incident report with timeline and response steps.
        """
        prompt = incident_summary_prompt(alerts)
        return await self._run("summary", prompt)

    async def explain_mitre(self, alert: dict) -> AIResult:
        """
        Explain the MITRE ATT&CK technique(s) referenced in an alert.
        Connects the technique to the specific evidence in the alert.
        """
        prompt = mitre_explanation_prompt(alert)
        return await self._run("mitre", prompt)

    async def recommend_actions(self, alert: dict) -> AIResult:
        """
        Generate a prioritized action plan for responding to an alert.
        Returns immediate, investigation, and remediation steps.
        """
        prompt = recommended_actions_prompt(alert)
        return await self._run("recommend", prompt)

    async def generate_executive_report(
        self,
        alerts: list[dict],
        period: str = "last 24 hours",
    ) -> AIResult:
        """
        Generate an executive-level security report for leadership.
        Non-technical, business-impact focused.
        """
        prompt = executive_report_prompt(alerts, period)
        return await self._run("report", prompt)

    async def generate_threat_narrative(self, alerts: list[dict]) -> AIResult:
        """
        Generate a threat narrative — the attack story from both
        attacker and defender perspectives.
        """
        prompt = threat_narrative_prompt(alerts)
        return await self._run("narrative", prompt)

    def get_stats(self) -> dict:
        return {**self._stats, "configured": self.is_configured}
