"""
reasoning/prompts.py — Prompt Templates for Gemini

All prompts enforce the core design constraint:
  Gemini only reasons about alerts that have ALREADY been generated
  by the detection engine (Sigma, correlation, ML).
  Gemini never decides whether something is malicious.
  Gemini only explains, summarizes, and recommends.

Each function takes structured alert data and returns a formatted prompt string.
The system instruction is shared across all prompt types.
"""

from __future__ import annotations

# ── System instruction (sent with every request) ──────────────────────────────

SYSTEM_INSTRUCTION = """You are an AI security analyst assistant for NanoSIEM, \
a detection engineering platform.

Your role is EXCLUSIVELY to explain, summarize, and provide context for \
security alerts that have ALREADY been generated by NanoSIEM's detection engine. \
The detection engine consists of Sigma rules, a correlation engine, and an \
Isolation Forest ML anomaly scorer.

STRICT CONSTRAINTS:
1. You NEVER determine whether something is malicious or benign. That decision \
was already made by the detection engine before you were called.
2. You NEVER suggest additional detection logic, Sigma rules, or ML thresholds.
3. You ONLY explain what happened, why it matters, and what an analyst should do next.
4. Be concise and actionable. Analysts are busy. No unnecessary preamble.
5. Use plain English. Avoid jargon unless the audience is explicitly technical.
6. Always reference the specific alert data provided — never make up details.
7. Format your response in clean Markdown."""


# ── Alert serializer (shared across all prompts) ──────────────────────────────

def _format_alert(alert: dict) -> str:
    """Format an alert dict into a readable prompt section."""
    lines = [
        f"**Alert Type:** {alert.get('alert_type', 'unknown').upper()}",
        f"**Title:** {alert.get('title', 'Unknown')}",
        f"**Severity:** {alert.get('severity', 'unknown').upper()}",
        f"**Source:** {alert.get('source_key', 'unknown')}",
        f"**Timestamp:** {alert.get('timestamp', 'unknown')}",
        f"**Times Seen:** {alert.get('hit_count', 1)}",
    ]

    if alert.get("event_message"):
        lines.append(f"**Triggering Log:** `{alert['event_message'][:300]}`")

    if alert.get("mitre_tactic"):
        lines.append(f"**MITRE Tactic:** {alert['mitre_tactic']}")

    if alert.get("mitre_techniques"):
        techs = ", ".join(alert["mitre_techniques"])
        lines.append(f"**MITRE Techniques:** {techs}")

    if alert.get("anomaly_score") and alert["anomaly_score"] > 0:
        lines.append(f"**ML Anomaly Score:** {alert['anomaly_score']:.3f} / 1.000")

    if alert.get("xai_features"):
        top = alert["xai_features"][:3]
        drivers = ", ".join(f"{f['feature']} ({f['deviation']:.2f})" for f in top)
        lines.append(f"**ML Top Drivers:** {drivers}")

    if alert.get("chain_steps"):
        lines.append("**Attack Chain Steps:**")
        for i, step in enumerate(alert["chain_steps"], 1):
            lines.append(f"  {i}. [{step.get('step', '?')}] {step.get('message', '')[:100]}")

    if alert.get("sigma_tags"):
        lines.append(f"**Sigma Tags:** {', '.join(alert['sigma_tags'][:5])}")

    if alert.get("duration_seconds") and alert["duration_seconds"] > 0:
        lines.append(f"**Attack Duration:** {alert['duration_seconds']:.0f} seconds")

    return "\n".join(lines)


# ── Prompt builders ───────────────────────────────────────────────────────────

def analyst_explanation_prompt(alert: dict) -> str:
    """
    Prompt for: analyst-level explanation of a single alert.
    Audience: L1/L2 SOC analyst.
    Output: what happened, why the alert fired, what to investigate next.
    """
    alert_text = _format_alert(alert)
    return f"""A security alert was generated by NanoSIEM's detection engine. \
Explain this alert to an L1 SOC analyst.

## Alert Details
{alert_text}

## Your Task
Provide a clear explanation covering:
1. **What happened** — describe the security event in plain English
2. **Why this alert fired** — explain what the detection engine saw \
(Sigma rule match, attack chain completion, or ML anomaly)
3. **Severity assessment** — why this severity level was assigned
4. **Immediate investigation steps** — 3-5 specific actions the analyst \
should take RIGHT NOW (check logs, isolate host, verify user, etc.)
5. **Escalation criteria** — under what conditions should this be escalated to L2/L3

Keep your response concise and actionable. The analyst needs to triage this \
in under 2 minutes."""


def incident_summary_prompt(alerts: list[dict]) -> str:
    """
    Prompt for: incident summary across multiple related alerts.
    Audience: incident responder or team lead.
    Output: what the full attack looks like, timeline, scope, recommendations.
    """
    if not alerts:
        return "No alerts provided."

    alerts_text = "\n\n---\n\n".join(
        f"### Alert {i+1}\n{_format_alert(a)}"
        for i, a in enumerate(alerts[:10])  # cap at 10
    )

    source_ips = list({a.get("source_key", "") for a in alerts if a.get("source_key")})
    severities = [a.get("severity", "") for a in alerts]
    types = list({a.get("alert_type", "") for a in alerts})

    return f"""NanoSIEM has generated {len(alerts)} security alerts that may \
be part of a coordinated attack. Provide an incident summary for the responding team.

## Alert Cluster
- **Total Alerts:** {len(alerts)}
- **Alert Types:** {', '.join(types)}
- **Severity Levels:** {', '.join(set(severities))}
- **Source IPs:** {', '.join(source_ips) or 'multiple'}

## Individual Alerts
{alerts_text}

## Your Task
Write a structured incident summary covering:
1. **Incident Overview** — 2-3 sentence executive summary of what is happening
2. **Attack Narrative** — describe the attack as a story with timeline \
(what did the attacker do, in what order, what were they trying to achieve)
3. **Affected Assets** — what hosts, accounts, and services are involved
4. **Attack Phase** — where in the kill chain is the attacker right now \
(recon / initial access / execution / persistence / exfiltration / etc.)
5. **Containment Actions** — immediate steps to stop the attack
6. **Evidence to Preserve** — what logs, artifacts, and forensic evidence \
should be collected now before it's lost
7. **Recovery Steps** — after containment, what needs to be done to restore normal operations

Format as a structured incident report."""


def mitre_explanation_prompt(alert: dict) -> str:
    """
    Prompt for: MITRE ATT&CK context for an alert.
    Audience: analyst who wants to understand the technique being used.
    Output: what the technique is, how attackers use it, how to detect/prevent.
    """
    techniques = alert.get("mitre_techniques", [])
    tactic = alert.get("mitre_tactic", "Unknown")
    alert_text = _format_alert(alert)

    if not techniques:
        techniques_str = "No specific technique identified"
    else:
        techniques_str = ", ".join(techniques)

    return f"""An alert mapped to MITRE ATT&CK technique(s) was generated. \
Explain the technique(s) in the context of this specific alert.

## Alert
{alert_text}

## Techniques Involved
Tactic: {tactic}
Techniques: {techniques_str}

## Your Task
For each MITRE ATT&CK technique referenced in this alert:
1. **What is this technique?** — explain what it means in plain English
2. **How attackers use it** — describe 2-3 real-world scenarios where this technique appears
3. **What we detected** — connect the technique to the specific alert evidence above
4. **Detection gaps** — what related sub-techniques or variations might NOT be caught
5. **Defensive measures** — 3-5 specific hardening actions to prevent this technique

Be specific to the alert context. Don't give generic ATT&CK descriptions — \
connect everything to what NanoSIEM actually detected."""


def recommended_actions_prompt(alert: dict) -> str:
    """
    Prompt for: prioritized recommended actions for a specific alert.
    Audience: analyst or incident responder who needs an action checklist.
    Output: structured action plan with priority and effort estimates.
    """
    alert_text = _format_alert(alert)
    return f"""Generate a prioritized action plan for responding to this security alert.

## Alert
{alert_text}

## Your Task
Provide a structured action plan with three sections:

### 🚨 IMMEDIATE (Do within 15 minutes)
List 3-5 actions that must happen right now to prevent escalation.
For each action: what to do, which system/tool to use, what you're looking for.

### 🔍 INVESTIGATE (Do within 1 hour)
List 5-8 investigation steps to understand the full scope.
Include: log sources to query, commands to run, indicators to hunt for.

### 🛡️ REMEDIATE (Do within 24 hours)
List 3-5 remediation and hardening actions after containment.
Include: configuration changes, patches, access reviews.

For each action, indicate:
- **Priority:** P1 (critical) / P2 (high) / P3 (medium)
- **Effort:** Quick (< 5 min) / Medium (5-30 min) / Extended (> 30 min)
- **Tool/System:** what tool or system is used for this action

Be specific. Reference the actual source IP, host, program, and message from the alert."""


def executive_report_prompt(alerts: list[dict], period: str = "last 24 hours") -> str:
    """
    Prompt for: executive-level incident report.
    Audience: CISO, management, non-technical stakeholders.
    Output: business-impact focused summary, no technical jargon.
    """
    total = len(alerts)
    critical = sum(1 for a in alerts if a.get("severity") == "critical")
    high = sum(1 for a in alerts if a.get("severity") == "high")
    types = list({a.get("alert_type", "") for a in alerts})
    sources = list({a.get("source_key", "") for a in alerts if a.get("source_key")})

    # Sample the most severe alerts for context
    sorted_alerts = sorted(
        alerts,
        key=lambda a: {"critical": 0, "high": 1, "medium": 2, "low": 3}.get(a.get("severity", "low"), 4)
    )
    top_alerts = sorted_alerts[:5]
    top_text = "\n\n".join(f"- {a.get('title')} ({a.get('severity', '').upper()})" for a in top_alerts)

    return f"""Write an executive security report for non-technical leadership.

## Detection Summary ({period})
- Total Alerts: {total}
- Critical Severity: {critical}
- High Severity: {high}
- Detection Methods Used: {', '.join(types)}
- Unique Sources (IPs/Hosts): {len(sources)}

## Most Significant Alerts
{top_text}

## Your Task
Write a professional executive report covering:

1. **Security Posture Summary** (2-3 sentences)
   High-level status: are we under active attack? contained? monitoring?

2. **Key Findings** (bullet points, plain English)
   What happened, avoiding technical jargon. Focus on business impact.

3. **Risk Assessment**
   What is the risk to the business if these threats are not addressed?
   What data, systems, or operations are at risk?

4. **Actions Taken**
   What has the security team done in response?

5. **Recommended Decisions for Leadership**
   2-3 decisions that require executive approval or awareness
   (budget, policy, external notification, legal, etc.)

6. **Next Steps**
   What will the security team do in the next 24-48 hours?

Tone: professional, clear, no acronyms without explanation, business-impact focused.
Length: 400-600 words. This will be read by the CISO and potentially the board."""


def threat_narrative_prompt(alerts: list[dict]) -> str:
    """
    Prompt for: storytelling narrative of a multi-alert attack sequence.
    Audience: technical analyst, threat hunter, or training material.
    Output: story of the attack written from the attacker's perspective.
    """
    if not alerts:
        return "No alerts provided."

    # Sort by timestamp
    sorted_alerts = sorted(alerts, key=lambda a: a.get("timestamp", 0))
    timeline = "\n".join(
        f"- T+{i*30}s: [{a.get('alert_type','?').upper()}] {a.get('title','?')} "
        f"(src: {a.get('source_key','?')})"
        for i, a in enumerate(sorted_alerts[:15])
    )

    all_techniques = list({
        tech
        for a in alerts
        for tech in (a.get("mitre_techniques") or [])
    })

    return f"""Write a threat narrative — tell the story of this attack as it \
unfolded, from the attacker's perspective.

## Alert Timeline
{timeline}

## MITRE Techniques Observed
{', '.join(all_techniques) if all_techniques else 'Not specified'}

## Your Task
Write a threat narrative in two parts:

### Part 1: The Attack Story (Attacker's Perspective)
Write as if you are narrating what the attacker did, in chronological order. \
Use present tense. Make it read like a threat intelligence report.
Example style: "The attacker begins with reconnaissance, scanning port 22 across \
the subnet. After identifying the target, they attempt credential brute-force..."

Focus on:
- Attacker motivation and objective (what were they after?)
- Tools and techniques used at each stage
- How each stage enabled the next
- What the attacker achieved (or failed to achieve)

### Part 2: Detection Story (Defender's Perspective)
Explain how NanoSIEM caught the attack at each stage:
- Which detection layer caught what (Sigma rule / correlation chain / ML anomaly)
- What was the first indicator? What was the pivotal alert?
- Were there any stages the attacker completed before detection?
- What would have happened if this went undetected?

Keep it engaging and educational. This may be used for security awareness training."""
